apiVersion: v1
kind: Service
metadata:
  name: grocery-app
  namespace: grocery
  labels:
    app.kubernetes.io/name: grocery-app
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grocery-app
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
